version: 2
jobs:
   build-xenial:
     docker:
       - image: circleci/buildpack-deps:xenial-scm
     environment:
       - OCPN_TARGET:  xenial
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-bionic:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     environment:
       - OCPN_TARGET:  bionic
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-buster:
     docker:
       - image: circleci/buildpack-deps:buster-scm
     environment:
       - OCPN_TARGET:  buster
     steps:
       - checkout
       - run: >
           echo "deb-src http://ftp.us.debian.org/debian buster main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://ftp.us.debian.org/debian buster-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-debian:
     docker:
       - image: circleci/buildpack-deps:xenial-scm
     environment:
       - OCPN_TARGET:  xenial
       - CLOUDSMITH_PKG_EXT: deb
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: bash ci/circleci-build-debian.sh
       - run: bash ci/circleci-upload.sh
   build-flatpak:
     machine:
       image: circleci/classic:201808-01
     environment:
       - OCPN_TARGET:  flatpak
       - CLOUDSMITH_PKG_EXT: gz
     steps:
       - checkout
       - run: bash ci/circleci-build-flatpak.sh
       - run: bash ci/circleci-upload.sh
       - store_test_results:
           path: ~/test-results
   build-fedora:
     docker:
         - image: fedora:29
     environment:
       - OCPN_TARGET:  fedora
     steps:
       - run: su -c "dnf install -q -y git openssh-clients openssh-server"
       - checkout
       - run: ci/circleci-build-fedora.sh
       - run: ci/circleci-upload.sh
   build-mingw:
     docker:
         - image: fedora:29
     environment:
       - OCPN_TARGET:  mingw
       - CLOUDSMITH_PKG_EXT: exe
     steps:
       - run: su -c "dnf install -q -y git openssh-clients openssh-server"
       - checkout
       - run: bash ci/circleci-build-mingw.sh
       - run: bash ci/circleci-upload.sh
   build-macos:
     macos:
       xcode: "10.0.0"
     environment:
       - OCPN_TARGET:  macos
       - CLOUDSMITH_PKG_EXT: pkg
     steps:
       - checkout
       - run: bash ci/circleci-build-macos.sh
       - run: bash ci/circleci-upload.sh
       - store_test_results:
           path: ~/test-results	   
workflows:
  version: 2
  build_all:
    jobs:
      - build-xenial:
          filters:
            branches:
              ignore:
                - devel
                - tmp
      - build-bionic:
          filters:
            branches:
              ignore:
                - devel
                - tmp
      - build-buster:
          filters:
            branches:
              ignore:
                - devel
                - tmp
      - build-flatpak:
          filters:
            branches:
              ignore:
                - devel
                - tmp
      - build-fedora:
          filters:
            branches:
              ignore:
                - devel
                - tmp
      - build-mingw:
          filters:
            branches:
              ignore:
                - devel
                - tmp
      - build-macos:
          filters:
            branches:
              ignore:
                - devel
                - tmp				
